require 'spec_helper'

describe WebCms::Chart::Data do

  subject { described_class.new(web_cms_data_stub) }
  let(:web_cms_data_stub) do
    [
      [10, 10, 50],
      [10, 10, 150],
      [10, 10, 250],
      [10, 10, 150]
    ]
  end

  its(:title) { should == 'Request Time'}
  its(:data) do
    should == { 'webcms' => [1, 2, 1] }
  end

  its(:labels) { should == ['0-99', '100-199', '200-299'] }

  it 'has labels (Array)'
  it 'should have a chart_type'
  it 'should be generated by a Factory'
end
