require 'spec_helper'

describe WebCms::Chart::Data do

  subject { described_class.new(web_cms_data_stub) }
  let(:web_cms_data_stub) do
    [
      [10, 10, 500.4],
      [10, 10, 1500.5],
      [10, 10, 2500.9],
      [10, 10, 1500.3]
    ]
  end

  its(:title) { should == 'Request Time'}
  its(:data) do
    should == { 'webcms (ms./req.)' => [1, 2, 1] }
  end

  its(:labels) { should == ['0-99', '100-199', '200-299'] }

  it 'should have a chart_type'
  it 'should be generated by a Factory'
end
