require 'spec_helper'

describe WebCms::Chart::Data do

  subject { described_class.new(web_cms_data_stub) }
  let(:web_cms_data_stub) do
    [
      [10, 10, 900.4],
      [10, 10, 5000.5],
      [10, 10, 10000.9],
      [10, 10, 5000.3]
    ]
  end

  its(:title) { should == 'Request Time'}
  its(:data) do
    should == { 'webcms (ms./req. +/- 50ms.)' => [1, 2, 1] }
  end

  its(:labels) { should == ['50', '550', '1,050'] }

  it 'should have a chart_type'
  it 'should be generated by a Factory'
end
